# Redirect beta with domain replacement but keep the URL path
http:
  routers:
    beta_router:
      rule: Host(`beta.choosefi.com`)
      entrypoints: web
      middlewares:
        - beta_redirect
      service: service_choosefi

  middlewares:
    beta_redirect:
      redirectRegex:
        regex: "^https?://beta.choosefi.com/(.*)"
        replacement: "https://www.choosefi.com/${1}"
        permanent: "true"


  services:
    service_choosefi:
      loadBalancer:
        servers:
        - url: https://wwww.choosefi.com/dont-go-here
        passHostHeader: false


